### ISSUE TITLE
Getting error "Cannot read property 'lookup' of undefined at ServerResponse.header" 

### ISSUE THREAD

**Issue by medhost-jshaver** [awslabs/fhir-works-on-aws-routing#158]
**Describe the bug**

Getting a 500 response from the fhirserver when building with the mainline branch's code. The error below is what the fhirServer throws.

This seems like a dependency issue. When the [setContentTypeMiddleware](https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/middlewares/setContentType.ts) is called mime.chartset.loopkup() is failing inside the express module because mine.charset is undefined. 

```
ERROR	Unhandled Error TypeError: Cannot read property 'lookup' of undefined
    at ServerResponse.header (/var/task/src/webpack:/node_modules/express/lib/response.js:771:1)
    at ServerResponse.contentType (/var/task/src/webpack:/node_modules/express/lib/response.js:604:1)
    at setContentTypeMiddleware (/var/task/src/webpack:/node_modules/fhir-works-on-aws-routing/lib/router/middlewares/setContentType.js:15:1)
    at Layer.handle [as handle_request] (/var/task/src/webpack:/node_modules/express/lib/router/layer.js:95:1)
    at trim_prefix (/var/task/src/webpack:/node_modules/express/lib/router/index.js:323:1)
    at /var/task/src/webpack:/node_modules/express/lib/router/index.js:284:1
    at Function.process_params (/var/task/src/webpack:/node_modules/express/lib/router/index.js:341:1)
    at next (/var/task/src/webpack:/node_modules/express/lib/router/index.js:275:1)
    at /var/task/src/webpack:/node_modules/fhir-works-on-aws-routing/lib/router/middlewares/setServerUrl.js:26:1
    at /var/task/src/webpack:/node_modules/fhir-works-on-aws-routing/lib/router/routes/routeHelper.js:16:1
```

**To Reproduce**
I am building fhirworks slightly differently than deployment package does by default. 

couple callouts:
- using npm install instead of yarn (lock files may be different that this repo)
- still using serverless package to package the lambda code -- so hopefully no difference here.
- I am using mainline branch for all packages except deployment. for deployment I am using smart-mainline. 

After building this and deploying to AWS all requests to the fhirserver receive the above error
GET `/tenant/{tenantId}/Patient` a simple request should return the error.

**Versions (please complete the following information):**
Using mainline for all the packages except deployment. For deployment I am using smart-mainline

I plan to try building fhirworks with the default install.sh found in the deployment package to see if I get the same dependency issue. I am still trying to determine if this is caused by the way I am packaging the fhirServer or not.

**Comment by medhost-jshaver** [comment]
This was caused by another package we created that has mime 2.6.0 as a dependency. I pinned mime 1.6.0 in the deployment package.json to correct this. Closing this issue
